### ISSUE TITLE
Weird Half Scroll on initial load on smaller viewport height

### ISSUE THREAD

**Issue by jordanrabidou** [alvarotrigo/multiscroll.js#136]
When viewing my site: https://waverlypensacola.com/ on a viewport height less than 790px the first screen loads but then the right half is put off screen. This is corrected if the site is scrolled or resized

https://www.loom.com/share/8e91a52cb48a4e018225d08de66e7604

**Comment by alvarotrigo** [comment]
Make sure to use the latest version of your scrollOverflow extension `scrollOverflow MultiScroll Extension 0.0.3`

**Comment by jordanrabidou** [comment]
Where can i get that?, the email I received only gives the option to download 0.1
<img width="942" alt="Screen Shot 2022-05-25 at 11 09 48 AM" src="https://user-images.githubusercontent.com/6352664/170296093-d9312ba7-aa0d-4b85-b7af-42e5eef35891.png">
<img width="1306" alt="Screen Shot 2022-05-25 at 11 09 34 AM" src="https://user-images.githubusercontent.com/6352664/170296094-4ff1b075-4cb9-4af3-85af-d1a55d6af305.png">

**Comment by alvarotrigo** [comment]
Try again, we've just uploaded it again in case there was some error.

**Comment by jordanrabidou** [comment]
still only getting version 0.0.1

Cleared cache and opened browser in incognito

Best,
Jordan Rabidou
------------------------
The Bananaland
www.thebananaland.com
162 Elm St.
Bridgeport CT. 06604
(203) 244-8345

**Comment by alvarotrigo** [comment]
Alright. Apologies for that :)
It should be fixed by now. Try again.

**Comment by jordanrabidou** [comment]
Thanks Alvaro,
So I’ve downloaded and implemented version 0.3 however the issue still exists.
Best,
Jordan Rabidou
------------------------
The Bananaland
www.thebananaland.com
162 Elm St.
Bridgeport CT. 06604
(203) 244-8345

**Comment by alvarotrigo** [comment]
I can't reproduce your issue. See the video below:

https://user-images.githubusercontent.com/1706326/170300128-4abd0a41-ec66-4fcc-8897-07acdb2b5c3e.mp4

**Comment by jordanrabidou** [comment]
here is another recording of what i'm seeing
https://www.loom.com/share/1b77e63f0ab94955a40bcda1f478f1ac

**Comment by jordanrabidou** [comment]
As you can see it only happens on the initial load of the site, if you resize the screen it fixes itself

**Comment by alvarotrigo** [comment]
Make sure to use the latest version of multiScroll 
 multiscroll.js 0.2.2 - Extensions 0.0.7

**Comment by alvarotrigo** [comment]
Make sure to use the latest version of multiScroll
multiscroll.js 0.2.2 - Extensions 0.0.7

**Comment by jordanrabidou** [comment]
Ok I’ve updated that as well.

Unfortunately, the same issue remains.

Best,
Jordan Rabidou
------------------------
The Bananaland
www.thebananaland.com
162 Elm St.
Bridgeport CT. 06604
(203) 244-8345

**Comment by alvarotrigo** [comment]
Can you provide an isolated reproduction?
No external JS code and CSS files and the minium amount of HTML code possible.

**Comment by jordanrabidou** [comment]
So I was able to isolate the issue to a scroll overflow on the last screen causing the issue. As a current workaround, I've shrunk all text and spacing to be much tighter as not to cause a scroll overflow on a realistic viewport height.

**Comment by alvarotrigo** [comment]
Can you provide a link to the isolated reproduction with no external code and the minimum amount of HTML?
